myapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuario.urls')),
    path('tarefas/', include('tarefas.urls')),
]

tarefas/urls.py
from django.urls import path
from tarefas import views

app_name="tarefas"

urlpatterns = [
    path("", views.home, name="home"),
    path("adicionar", views.adicionar, name="adicionar"),
    path("<int:id_item>/editar", views.editar, name="editar"),
    path("<int:id_item>/deletar_tarefa", views.deletar_tarefa, name="deletar_tarefa"),
]

usuario/urls.py
from django.urls import path
from usuario import views

app_name = 'usuario'

urlpatterns = [
    path("", views.index, name="index"),
    path("cadastrar_usuario", views.cadastrar_usuario, name="cadastrar_usuario"),
    path("login_user", views.login_user, name="login_user"),
    path("logout_user", views.logout_user, name="logout_user"),
]

tarefas/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class ListaTarefas(models.Model):
    nome = models.CharField(max_length=64)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="usuario_lista", null=True)
    descricao = models.TextField(max_length=300)
    realizada = models.BooleanField(null=True, verbose_name="Realizada?")


    def __str__(self) -> str:
        return self.nome

usuario/models.py
from django.db import models

# Create your models here.

tarefas/forms.py
from django.forms import ModelForm, widgets
from tarefas.models import ListaTarefas



class ListaTarefasForm(ModelForm):
    class Meta():
        model = ListaTarefas
        fields = ['nome', 'descricao', 'realizada']
        widgets = {
            'realizada': widgets.CheckboxInput(attrs={'class': 'form-check-input'} ),

        }

usuario/forms.py
from django import forms

class UsuarioForm(forms.Form):
    nome = forms.CharField(label="Nome", max_length=64, error_messages={ 
                 'required':"Please Enter your Name"
                 })
    email = forms.EmailField(label="Email", max_length=128)
    senha = forms.CharField(label="Senha" ,widget=forms.PasswordInput, min_length=8)
    senha2 = forms.CharField(label="digite a senha novamente" ,widget=forms.PasswordInput, min_length=8)

    def clean(self):
        self.cleaned_data = super().clean()
        pass1 = self.cleaned_data['senha']
        pass2 = self.cleaned_data['senha2']
        if pass1 != pass2:
            raise forms.ValidationError("Senhas não são iguais")

class LoginForm(forms.Form):
    nome = forms.CharField(label="Nome", max_length=64)
    senha = forms.CharField(label="Senha", min_length=8, widget=forms.PasswordInput())

tarefas/views.py
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from tarefas.models import ListaTarefas
from tarefas.forms import ListaTarefasForm
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
# Create your views here.

@login_required
def home(request):

    lista = ListaTarefas.objects.filter(usuario=request.user)
    return render(request, "tarefas/home.html", {
        "lista": lista,
    })

@login_required
def adicionar(request):

    if request.method == 'POST':
        nome = request.POST['nome']
        descricao = request.POST['descricao']
        concluida = False
        if 'realizada' in request.POST:
            concluida = True
        tarefa = ListaTarefas(nome=nome, usuario=request.user , descricao=descricao, realizada=concluida)
        tarefa.save()
        return redirect("tarefas:home")

    return render(request, "tarefas/adicionar.html", {
        "form": ListaTarefasForm(),
    })   

@login_required
def editar(request, id_item):

    item = ListaTarefas.objects.get(pk=id_item)
    if request.user != item.usuario:
        raise PermissionDenied
    if request.method == 'POST':
        item_editado = request.POST
        item.nome = item_editado['nome']
        item.descricao = item_editado['descricao']
        if 'realizada' in request.POST:
            item.realizada = True
        else:
            item.realizada = False
        item.save()
        return redirect("tarefas:home")
    return render(request, "tarefas/editar.html", {
        "item": item
    })


@login_required
def deletar_tarefa(request, id_item):
    if request.method == 'POST':
        item = ListaTarefas.objects.get(pk=id_item)
        if request.user != item.usuario:
            raise PermissionDenied
        item.delete()
    return redirect("tarefas:home")

usuario/views.py
from django.shortcuts import redirect, render
from .forms import UsuarioForm, LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def index(request):
    if request.user.is_authenticated:
        return redirect("tarefas:home")

    return render(request, "usuario/index.html")


def cadastrar_usuario(request):

    if request.user.is_authenticated:
        return redirect("tarefas:home")

    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        if form.is_valid():
            nome = form.cleaned_data['nome']
            email = form.cleaned_data['email']
            senha = form.cleaned_data['senha']
            user = User.objects.create_user(nome, email, senha)
            user.save()
            return redirect("usuario:index")
    
    return render(request, "usuario/cadastrar_usuario.html", {
        "form": UsuarioForm()
    })


def login_user(request):

    if request.user.is_authenticated:
        return redirect("tarefas:home")

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            nome = form.cleaned_data['nome']
            senha = form.cleaned_data['senha']
            user = authenticate(username=nome, password=senha)
            if user:
                login(request, user)
                return redirect("tarefas:home")
            else:
                return render(request, "usuario/login.html", {
                    "form": LoginForm(),
                    "mensagem": "Usuário ou senha está incorreto"
                })

    return render(request, "usuario/login.html", {
        "form": LoginForm()
    })


def logout_user(request):
    logout(request)
    return redirect("usuario:index")

assets/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MeuApp</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">	
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header>
    	<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
        <div class="container-fluid">
        	<a href="{% url 'usuario:index' %}" class="navbar-brand">
				{% if not user.is_authenticated %}<h2>Início</h2> {% else %}<h2>{{user.username}}</h2> {% endif %}</a>
          	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">				
            	<span class="navbar-toggler-icon"></span>
          	</button>
          	<div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
				{% if not user.is_authenticated %}
				<li class="nav-item"><a class="nav-link" href="#">Sobre nós</a></li>
				<li class="nav-item"><a class="nav-link" href="#">Contato</a></li>
				<li class="nav-item"><a class="nav-link" href="{% url 'usuario:cadastrar_usuario' %}">Cadastre-se!</a></li>
				<li class="nav-item"><a class="nav-link" href="{% url 'usuario:login_user' %}">Login</a></li>
				{% else %}
				<li class="nav-item"><a class="nav-link" href="{% url 'tarefas:home' %}">Home</a></li>
				<li class="nav-item"><a class="nav-link" href="{% url 'tarefas:adicionar' %}">Criar tarefa</a></li>
				<li class="nav-item"><a class="nav-link" href="{% url 'usuario:logout_user' %}">Logout</a></li>
				{% endif %}
			</ul>
            </div>
        </div>
        </nav>
	</header>
	<main>
    {% block body %}
	{% endblock %}
	</main>
	{% if not user.is_authenticated %}
    <footer>
		<div class="container-fluid padding">
			<div class="row text-center">
				<div class="col-md-4">
					<h3>Logo</h3>
					<hr class="light">
					<p>(49)99999-9999</p>
					<p>email@myemail.com</p>
					<p>rua tal, bairo tal, nº 000</p>
					<p>Lages-SC,88500-000</p>
				</div>
				<div class="col-md-4">
					<hr class="light">
					<h5>Nossos horários</h5>
					<hr class="light">
					<p>Segunda à Sexta: 9:00 - 17:00</p>
					<p>Sábado: 10:00 - 16:00</p>
					<p>Domingo: fechado</p>
				</div>
				<div class="col-md-4">
					<hr class="light">
					<h5>Lojas</h5>
					<hr class="light">
					<p>Cidade, Estado, 99000-000</p>
					<p>Cidade, Estado, 99000-000</p>
					<p>Cidade, Estado, 99000-000</p>
					<p>Cidade, Estado, 99000-000</p>
				</div>
				<div class="col-12">
					<hr class="light-100">
					<h5>&copy; neimar.com</h5>
				</div>
			</div>
		</div>
	</footer>
	{% endif %}
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
	<script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
	<!-- <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script> -->
	<!-- <script src="{% static 'js/site.js' %}"></script> -->
</body>
</html>

tarefas/templates/tarefas/adicionar.html
{% extends 'layout.html' %}
{% load bootstrap %}
{% load static %}

{% block body %}
<form action="{% url 'tarefas:adicionar' %}" method="POST">{% csrf_token %}
    <div class="form-wrap">
        <div class="form-group">
            <label for="nome">Tarefa:</label>
            <input type="text" class="form-control" name="nome" id="nome" value="{{item.nome}}"> 
        </div>
        <div class="form-group">
        <label for="descricao">Descrição:</label>
        <textarea name="descricao" class="form-control" id="descricao" cols="30" rows="10">{{item.descricao}}</textarea>
        </div>
        <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" name="realizada" id="realizada">
        <label class="form-check-label" for="realizada">Realizada?</label>
        </div>
        <button type="submit" class="btn btn-success btn-lg">Salvar tarefa</button>
    </div>
</form>
{% endblock %}

tarefas/templates/tarefas/editar.html
{% extends 'layout.html' %}
{% load static %}

{% block body %}

<form action="{% url 'tarefas:editar' id_item=item.id %}" method="POST">{% csrf_token %}
    <div class="form-wrap">
        <div class="form-group">
            <label for="nome">Tarefa:</label>
            <input type="text" class="form-control" name="nome" id="nome" value="{{item.nome}}"> 
        </div>
        <div class="form-group">
        <label for="descricao">Descrição:</label>
        <textarea name="descricao" class="form-control" id="descricao" cols="30" rows="10">{{item.descricao}}</textarea>
        </div>
        <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" name="realizada" id="realizada" checked>
        <label class="form-check-label" for="realizada">Realizada?</label>
        </div>
        <button type="submit" class="btn btn-success btn-lg">Editar</button>
    </div>
</form>

{% endblock %}

tarefas/templates/tarefas/home.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}

<div class="container-fluid col-sm-12 col-lg-8 my-5 mx-auto form-wrap">
{% if lista %}
<div class="table-responsive">
    <h1>Tarefas:</h1>
    <table class="table table-striped table-dark">
        <caption>Tarefas</caption>
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Tarefa</th>
                <th scope="col">Descrição</th>
                <th scope="col">Realizada?</th>
                <th scope="col">Editar</th>
                <th scope="col">Deletar</th>
            </tr>
            <tbody>
                {% for item in lista %}
                <tr>
                    <th scope="row">{{item.id}}</th>
                    <td>{{item.nome}}</td>
                    <td>{{item.descricao}}</td>
                    <td>{% if item.realizada %} Sim {% else %} Não {% endif %}</td>
                    <td><a href="{% url 'tarefas:editar' id_item=item.id %}" class="btn btn-secondary btn-sm "><i class="fas fa-edit"></i></a></td>
                    <td>
                        <form action="{% url 'tarefas:deletar_tarefa' id_item=item.id %}" method="POST">{% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-trash-alt"></i></button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </thead>
    </table>
</div>
{% else %}
<div class="text-center">
    <h1>Parabéns!</h1>
    <h2>Não há nenhuma tarefa cadastrada</h2>
    <img src="{% static 'img/gif/homer.gif' %}" alt="gif of homer simpson" class="gif">
</div>
{% endif %}
</div>
{% endblock %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MeuApp</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">	
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header>
    	<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
        <div class="container-fluid">
        	<a href="{% url 'usuario:index' %}" class="navbar-brand">
				{% if not user.is_authenticated %}<h2>Início</h2> {% else %}<h2>{{user.username}}</h2> {% endif %}</a>
          	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">				
            	<span class="navbar-toggler-icon"></span>
          	</button>
          	<div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
				{% if not user.is_authenticated %}
				<li class="nav-item"><a class="nav-link" href="#">Sobre nós</a></li>
				<li class="nav-item"><a class="nav-link" href="#">Contato</a></li>
				<li class="nav-item"><a class="nav-link" href="{% url 'usuario:cadastrar_usuario' %}">Cadastre-se!</a></li>
				<li class="nav-item"><a class="nav-link" href="{% url 'usuario:login_user' %}">Login</a></li>
				{% else %}
				<li class="nav-item"><a class="nav-link" href="{% url 'tarefas:home' %}">Home</a></li>
				<li class="nav-item"><a class="nav-link" href="{% url 'tarefas:adicionar' %}">Criar tarefa</a></li>
				<li class="nav-item"><a class="nav-link" href="{% url 'usuario:logout_user' %}">Logout</a></li>
				{% endif %}
			</ul>
            </div>
        </div>
        </nav>
	</header>
	<main>
    {% block body %}
	{% endblock %}
	</main>
    <footer>
		<div class="container-fluid padding">
			<div class="row text-center">
				<div class="col-md-4">
					<img src="{% static 'img/w3newbie.png' %}" alt="">
					<hr class="light">
					<p>(49)99999-9999</p>
					<p>email@myemail.com</p>
					<p>rua tal, bairo tal, nº 000</p>
					<p>Lages-SC,88500-000</p>
				</div>
				<div class="col-md-4">
					<hr class="light">
					<h5>Nossos horários</h5>
					<hr class="light">
					<p>Segunda à Sexta: 9:00 - 17:00</p>
					<p>Sábado: 10:00 - 16:00</p>
					<p>Domingo: fechado</p>
				</div>
				<div class="col-md-4">
					<hr class="light">
					<h5>Lojas</h5>
					<hr class="light">
					<p>Cidade, Estado, 99000-000</p>
					<p>Cidade, Estado, 99000-000</p>
					<p>Cidade, Estado, 99000-000</p>
					<p>Cidade, Estado, 99000-000</p>
				</div>
				<div class="col-12">
					<hr class="light-100">
					<h5>&copy; neimar.com</h5>
				</div>
			</div>
		</div>
	</footer>
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
	<script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
	<script src="{% static 'js/site.js' %}"></script>
</body>
</html>

usuario/templates/usuario/cadastrar_usuario.html
{% extends 'layout.html' %}
{% load static %}
{% load bootstrap %}



{% block body %}
    <form action="{% url 'usuario:cadastrar_usuario' %}" method="POST">{% csrf_token %}
        <div class="form-wrap" id="form-cadastro">
            {{ form|bootstrap }}
        <button class="btn btn-success btn-lg" id="btn-cadastrar-usuario" type="submit">Enviar</button>
        </div>
    </form>
{% endblock %}

usuario/templates/usuario/index.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}

<div id="slides" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'img/background.png' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
              <h1 class="display-2">Projeto Django</h1>
            <h3>Cadatro de usuários, login, criação, visualização e exclusão de tarefas para cada usuário </h3>
            <a class="btn btn-outline-light btn-lg" href="{% url 'usuario:cadastrar_usuario' %}">CADASTRE-SE</a>
            <a class="btn btn-primary btn-lg" href="{% url 'usuario:login_user' %}">Faça login</a>
        </div>
      </div>
    </div>
  </div>


  <div class="container-fluid padding">
      <div class="row welcome text-center">
          <div class="col-12">
              <h1 class="display-4">Just some Cards</h1>
          </div>
      </div>
  </div>

<!--- Cards -->
  <div class="container-fluid padding">
      <div class="row padding">
          <div class="col-md-4">
              <div class="card">
                  <img src="{% static 'img/team1.png' %}" alt="" class="card-img-top">
                  <div class="card-body">
                      <h4 class="card-title">John Dee</h4>
                      <p class="card-text">Lorem ipsum dolor sit amet consectetur, adipisicing elit.</p>
                      <a href="" class="btn btn-outline-secondary">See Profile</a>
                  </div>
              </div>
          </div>
          <div class="col-md-4">
              <div class="card">
                  <img src="{% static 'img/team2.png' %}" alt="" class="card-img-top">
                  <div class="card-body">
                      <h4 class="card-title">Mary Joe</h4>
                      <p class="card-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                      </p>
                      <a href="" class="btn btn-outline-secondary">See Profile</a>
                  </div>
              </div>
          </div>
          <div class="col-md-4">
              <div class="card">
                  <img src="{% static 'img/team3.png' %}" alt="" class="card-img-top">
                  <div class="card-body">
                      <h4 class="card-title">Phill Hoe</h4>
                      <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                      <a href="" class="btn btn-outline-secondary">See Profile</a>
                  </div>
              </div>
          </div>
      </div>
  </div>

<!--- Two Column Section -->
<div class="container-fluid padding">
    <div class="row padding">
        <div class="col-lg-6">
            <h2>Our Philosophy</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Corrupti dolorum nihil provident ad laborum atque porro dolore dignissimos, 
               veniam corporis vero asperiores nobis est voluptas in minima maiores? Maiores, placeat.
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                 Corrupti dolorum nihil provident ad laborum atque porro dolore dignissimos, 
                veniam corporis vero asperiores nobis est voluptas in minima maiores? Maiores, placeat.</p>
            <br>
            <a href="#" class="btn btn-primary">Learn more</a>
        </div>
        <div class="col-lg-6">
            <img src="{% static 'img/bootstrap2.png' %}" alt="" class="img-fluid">
        </div>
    </div>
</div>
<hr class="my-4">

<!--- Connect -->
<div class="container-fluid padding">
    <div class="row text-center padding">
        <div class="col-12">
            <h2>Connect</h2>
        </div>
        <div class="col-12 social padding">
            <a href="#"><i class="fab fa-facebook h"></i></a>
            <a href="#"><i class="fab fa-twitter h"></i></a>
            <a href="#"><i class="fab fa-google-plus-g h"></i></a>
            <a href="#"><i class="fab fa-instagram h"></i></a>
            <a href="#"><i class="fab fa-youtube h"></i></a>
        </div>
    </div>
</div>
{% endblock %}

usuario/templates/usuario/login.html
{% extends 'layout.html' %}

{% load bootstrap %}
{% load static %}

{% block body %}



<div class="container">
<div class="login-content">
<div class="card m-5">
    {% if mensagem %}
    <strong class="alert alert-danger" role="alert">{{ mensagem }}</strong> 
    {% endif %}
    <form action="{% url 'usuario:login_user' %}" method="POST">
        {% csrf_token %}
        <div class="form-group form-wrap">
        <h2 class="title">Bem vindo</h2>
           <div class="input-div one">
              <div class="i">
                      <i class="fas fa-user"></i>
              </div>
              <div class="div">
                      {{ form.nome|bootstrap }}
              </div>
           </div>
           <div class="input-div pass">
              <div class="i"> 
                   <i class="fas fa-lock"></i>
              </div>
              <div class="div">
                   {{ form.senha|bootstrap }}
           </div>
        </div>
        <button type="submit" class="btn btn-primary btn-lg">Login</button>
        </div>
    </form>
</div>
</div>
</div>




{% endblock %}